import type { WebPlayerSearchType } from '@/features/Search/api/client'
import type { BrowseCategory } from '@/features/Search/model/types'

export const searchTypes: WebPlayerSearchType[] = [
  'tracks',
  'albums',
  'playlists',
]

export const browseImages = [
  '/images/browse/browse-music.jpeg',
  '/images/browse/browse-podcasts.jpeg',
  '/images/browse/browse-liveevents.jpg',
  '/images/browse/browse-fitness.jpeg',
  '/images/browse/browse-foryou.jpeg',
  '/images/browse/browse-newrealease.jpeg',
  '/images/browse/browse-pop.jpeg',
  '/images/browse/browse-hiphop.jpeg',
] as const

const browseColors = [
  '#dc148c',
  '#006450',
  '#8400e7',
  '#777777',
  '#1e3264',
  '#608108',
  '#477d95',
  '#477d95',
  '#006450',
  '#e1338b',
  '#8d67ab',
  '#477d95',
  '#e1338b',
  '#af2896',
  '#dc148c',
  '#477d95',
  '#b06239',
  '#e03131',
  '#777777',
  '#8d67ab',
  '#b06216',
  '#b06216',
  '#e03131',
  '#3273dc',
] as const

const browseCategoryTitles = [
  'Music',
  'Podcasts',
  'Live Events',
  'Fitness',
  'Made For You',
  'New Releases',
  'Pop',
  'Hip-Hop',
  'Rock',
  'Mood',
  'Charts',
  'Comedy',
  'Educational',
  'True Crime',
  'Sports',
  'Dance / Electronic',
  'Chill',
  'Indie',
  'Workout Music',
  'Discover',
  'Folk & Acoustic',
  'R&B',
  'K-pop',
  'Latin',
  'Sleep',
  'Party',
  'At Home',
  'Decades',
  'Love',
  'Metal',
  'Jazz',
  'Trending',
  'Classical',
  'Country',
  'Focus',
  'Soul',
  'Kids & Family',
  'Gaming',
  'Anime',
  'TV & Movies',
  'Instrumental',
  'Wellness',
  'Punk',
  'Ambient',
  'Blues',
  'Cooking & Dining',
  'Alternative',
  'Travel',
  'Caribbean',
  'Afro',
  'Songwriters',
  'Nature & Noise',
  'Funk & Disco',
  'GLOW',
  'Spotify Singles',
  'Netflix',
  'Summer',
  'RADAR',
  'EQUAL',
  'Fresh Finds',
  'Mixed By',
] as const

export const searchFilterTabs = [
  'All',
  'Playlists',
  'Songs',
  'Genres & Moods',
  'Albums',
  'Profiles',
  'Artists',
  'Podcasts & Shows',
] as const

export const browseCategories: BrowseCategory[] = browseCategoryTitles.map(
  (title, index) => ({
    color: browseColors[index % browseColors.length] ?? '#477d95',
    image: browseImages[index % browseImages.length] ?? browseImages[0],
    title,
  }),
)

export const mockCategoryRows: Record<string, string[]> = {
  'Live Events': [
    'Concerts near you',
    'Electronic nights',
    'Festival season',
    'Indie stages',
    'Pop live',
  ],
  Podcasts: [
    'Comedy',
    'Educational',
    'True Crime',
    'Sports',
    'Stories',
    'Music',
    'Arts & Entertainment',
  ],
  Fitness: [
    'Workout hits',
    'Running',
    'Yoga',
    'Beast mode',
    'Cardio',
    'Morning energy',
  ],
}
