import type { Metadata } from 'next'
import { Source_Sans_3 } from 'next/font/google'
import { QueryClientProvider } from '@tanstack/react-query'
import { queryClient } from '@shared/api'
import { PropsWithChildren } from 'react'

import '@spotify/ui/globals.css'
import "./global.css";

const sourceSans = Source_Sans_3({
  variable: '--font-source-sans'
})

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo'
}

export default function RootLayout({
  children
}: PropsWithChildren) {
  const lang = 'en'

  return (
    <html lang={lang}>
      <body className={`${sourceSans.variable}`}>
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}
