import type { Metadata } from 'next'

import 'normalize.css'

import { Titillium_Web } from 'next/font/google'
import './globals.scss'

const WF_titillium_web = Titillium_Web({
	subsets: ['latin'],
	weight: '400',
	variable: '--wf-titilium'
})

export const metadata: Metadata = {
	title: 'Spotify clone',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={WF_titillium_web.className}>
			</body>
		</html>
	)
}
