import { QueryClientProvider } from '@shared/api/reactQueryClient'
import { AuthProvider } from '@shared/hooks'
import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'
import type { ReactNode } from 'react'

import './global.css'

const leagueSpartan = League_Spartan({
  variable: '--font-league-spartan',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: '@bitrate/artists',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  const lang = 'en'

  return (
    <html data-scroll-behavior="smooth" lang={lang}>
      <body className={`${leagueSpartan.variable} antialiased`}>
        <QueryClientProvider>
          <AuthProvider>{children}</AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
