import type { Metadata } from 'next'
import { Source_Sans_3 } from 'next/font/google'

import './globals.css'

const sourceSans = Source_Sans_3({
  variable: '--font-source-sans',
  subsets: ['latin', 'latin-ext'],
})

export const metadata: Metadata = {
  title: '@spotify/artists',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const lang = 'en'

  return (
    <html lang={lang} data-scroll-behavior="smooth">
      <body className={`${sourceSans.variable} antialiased`}>{children}</body>
    </html>
  )
}
