name: "[admin] Reusable"

on:
  workflow_call:
    inputs:
      push-image:
        description: Push admin image
        required: true
        type: boolean
      image-tags:
        description: Docker tags for admin image (multiline)
        required: true
        type: string
      timeout-minutes:
        description: Timeout for build job
        required: false
        default: 15
        type: number

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: lordpluha/${{ github.event.repository.name }}

jobs:
  admin-build:
    name: Admin Build
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker + registries
        uses: ./.github/actions/setup-docker
        with:
          ghcr: "true"
          ghcr-registry: ${{ env.REGISTRY }}
          ghcr-username: ${{ github.actor }}
          ghcr-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Admin Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/admin/Dockerfile
          push: ${{ inputs.push-image }}
          tags: ${{ inputs.image-tags }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/cache/admin:buildcache
            type=gha,scope=admin
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/cache/admin:buildcache,mode=max
            type=gha,mode=max,scope=admin
          target: production
