name: "[ui-react] Reusable"

on:
  workflow_call:
    inputs:
      run-biome:
        description: Run biome check before Loki
        required: false
        default: true
        type: boolean

jobs:
  biome:
    if: ${{ inputs.run-biome }}
    name: UI React Biome
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Run Biome check
        run: pnpm exec biome ci packages/ui-react

  loki-with-biome:
    if: ${{ inputs.run-biome }}
    needs: biome
    uses: ./.github/workflows/loki_reusable.yml

  loki-no-biome:
    if: ${{ !inputs.run-biome }}
    uses: ./.github/workflows/loki_reusable.yml
