name: "[ui-react][develop] Visual Tests"

on:
  push:
    branches: [develop]
    paths:
      - 'packages/ui-react/**'
      - '.github/workflows/ui_react_develop.yml'
      - '.github/workflows/loki_reusable.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  loki:
    uses: ./.github/workflows/loki_reusable.yml
