name: "[docker] Web Integration Test"

on:
  pull_request:
    branches: [master, develop]
    paths:
      - 'docker-compose*.yaml'
      - 'apps/api/**'
      - 'apps/web-player/**'
      - 'apps/web-artists/**'
      - 'apps/admin/**'
      - '.github/workflows/web-integration-test.yml'
      - '.github/workflows/web-integration-test_reusable.yml'
      - '.github/actions/setup-docker/**'
  push:
    branches: [develop, master]
    paths:
      - 'docker-compose*.yaml'
      - 'apps/api/**'
      - 'apps/web-player/**'
      - 'apps/web-artists/**'
      - 'apps/admin/**'
      - '.github/workflows/web-integration-test.yml'
      - '.github/workflows/web-integration-test_reusable.yml'
      - '.github/actions/setup-docker/**'
  workflow_dispatch:

jobs:
  integration-test:
    uses: ./.github/workflows/web-integration-test_reusable.yml
